server:
  port: 8080
spring:
  application:
    name: spring-security-basic
  datasource:
    username: postgres
    password: 2002sep24
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring-security-v2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop # or update
    generate-ddl: true
